name: SpeedRunCountPlugin
version: 1.1
main: com.ahhmino.speedRunCountPlugin.SpeedRunCountPlugin
api-version: 1.16
author: Amin Halimah
description: Displays configurable per-player and global item counts in a scoreboard.

commands:
  speedruncount:
    description: Reloads the SpeedRunCount plugin configuration.
    usage: /speedruncount reload
    permission: speedruncount.reload

permissions:
  speedruncount.reload:
    description: Allows reloading the plugin configuration.
    default: op
